name: musicsaur
description: The simplest music synchronization for multi-room audio.
meta_description: "Musicsaur is a open-source solution for simple music synchronization that provides multi-room audio with Raspberry Pis"

aboutPage: true

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://www.musicsaur.com'
google_analytics: 'UA-2345677-11'
disqus: true
disqus_shortname: 'musicsaur'

# Details for the RSS feed generator
url:            'http://www.musicsaur.com'
author:         '<span style="font-size: 200%;"><i>musicsaur</i></span>'
authorTwitter:  'zack_118'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems:
  - jekyll-sitemap
